### ISSUE TITLE
Memory allocation issues when using corrupted bloomfilter files

### ISSUE THREAD

**Issue by wllm-rbnt** [hashlookup/fleur#10]
fleur allocates large amounts of memory when using corrupted bloomfilter files on insertion.
Cfr attached gzipped files:
[hang0_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207520/hang0_insert.bin.gz)
[hang1_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207521/hang1_insert.bin.gz)
[hang2_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207522/hang2_insert.bin.gz)

This can be tested using the following command:
```echo bla | ./fleurcli -c insert hang0_insert.bin```

The last one, ```hang2_insert.bin```, is fixed by https://github.com/hashlookup/fleur/pull/9

**Comment by wllm-rbnt** [comment]
[hang0_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207520/hang0_insert.bin.gz) are [hang1_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207521/hang1_insert.bin.gz) are still problematic. Those ones are not fixed by PR #9, only the last one :).

**Comment by gallypette** [comment]
let's reopen then ;)

**Comment by wllm-rbnt** [comment]
Same behavior with the 'check' command on these files.
