### ISSUE TITLE
fleur segfaults on insertion using corrupted bloomfilter files

### ISSUE THREAD

**Issue by wllm-rbnt** [hashlookup/fleur#11]
fleur segfauts on insertion with the following corrupted (gzipped) bloomfilter files:
[crash0_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207722/crash0_insert.bin.gz)
[crash1_insert.bin.gz](https://github.com/hashlookup/fleur/files/9207723/crash1_insert.bin.gz)

The command used to reproduce the crashes is ```echo bla | ./fleurcli -c insert crash0_insert.bin```

Valgind output:
```
[...]
==1424957== Invalid read of size 8
==1424957==    at 0x403D94: Add (fleur.c:116)
==1424957==    by 0x40221E: main (fleurcli.c:147)
==1424957==  Address 0x233413bc23a9218 is not stack'd, malloc'd or (recently) free'd
[...]
```

**Comment by wllm-rbnt** [comment]
Same behavior with the 'check' command on these files.

```
==1425345== Invalid read of size 8
==1425345==    at 0x404333: Check (fleur.c:145)
==1425345==    by 0x401FC2: main (fleurcli.c:139)
==1425345==  Address 0x1e55d0ead154bd58 is not stack'd, malloc'd or (recently) free'd
```

**Comment by gallypette** [comment]
fixed by https://github.com/hashlookup/fleur/commit/a2428847ee271f5681c7f189bcfea8604a427d99
